image: node:12

stages:   
  - test

test:   
  stage: test   
  script:    
    - npm ci
    - npm run lint
    - npm run test
  tags:     
    - docker

test_10:
  stage: test
  script:
    - nvm install 10
    - nvm use 10
    - npm ci
    - npm run lint
    - npm run test
  tags:
    - docker
    - nvm
